//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccMon
    {
        public int Id { get; set; }
        public Nullable<int> GrpCode { get; set; }
        public Nullable<int> KolCode { get; set; }
        public string MonCode { get; set; }
        public string MonDscp { get; set; }
    }
}
