//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dr_Actions
    {
        public int serial { get; set; }
        public Nullable<int> FishPriority { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<int> Loan { get; set; }
        public string ReportName { get; set; }
    }
}
