//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataActivity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceDBEntities : DbContext
    {
        public FinanceDBEntities()
            : base("name=FinanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accGeneral> accGenerals { get; set; }
        public virtual DbSet<AccSobidiary> AccSobidiaries { get; set; }
        public virtual DbSet<WagEmployee> WagEmployees { get; set; }
        public virtual DbSet<Dr_Actions> Dr_Actions { get; set; }
        public virtual DbSet<AccGroup> AccGroups { get; set; }
        public virtual DbSet<AccKol> AccKols { get; set; }
        public virtual DbSet<AccMon> AccMons { get; set; }
    }
}
