//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WagEmployee
    {
        public int Serial { get; set; }
        public int NezamNo { get; set; }
        public string PersCode { get; set; }
        public string FatherName { get; set; }
        public string CertNo { get; set; }
        public string CertCode { get; set; }
        public string NationalCode { get; set; }
        public string BirthDate { get; set; }
        public string BirthLocation { get; set; }
        public string Gender { get; set; }
        public string BirthCertLoc { get; set; }
        public string AccountNo { get; set; }
        public string CardNo { get; set; }
        public string EmpType { get; set; }
        public Nullable<int> ProfRef { get; set; }
        public string Zarib { get; set; }
        public string FishAmount { get; set; }
        public string Aghidati { get; set; }
        public string OtaghAmal { get; set; }
        public string KosorBimarestan { get; set; }
        public string BldGpType { get; set; }
        public string PersName { get; set; }
    }
}
